---
- block:
    - name: Redhat subscription
      ansible.builtin.include_tasks: "5_redhat_sub.yml"

    - name: AAP setup
      ansible.builtin.include_tasks: "10_aap_setup.yml"
      tags:
        - aap_setup

  when: not pre_build|bool

- block:
    - name: AAP Signing bits included?
      ansible.builtin.set_fact:
        aap_signing_bits_included: "{{ __aap_version is version('2.2.0', '>=')  }}"

    - name: Setup signing
      ansible.builtin.include_tasks: "20_setup_signing.yml"

  when: not pre_build|bool and
        enable_signing|bool

# Have to install this to prevent std_callback errors
- name: Install packages
  ansible.builtin.include_tasks: 15_package_dependencies.yml
  when: not teardown

- name: Install hub
  ansible.builtin.include_tasks: "30_hub.yml"
  when: not pre_build|bool
