---
- name: Set host private ip to ip of the machine
  ansible.builtin.set_fact:
    __host_private_ip: '{{ ansible_default_ipv4["address"] }}'

- name: Template inventory file for Ansible Controller Install
  ansible.builtin.template:
    src: "hub_install.j2"
    dest: "{{ aap_dir }}/inventory"
  no_log: true

# sean note to self... should I remove the gpgcheck=0?
- name: Run the Automation Hub installer
  ansible.builtin.shell: "{{ controller_install_command }}"
  args:
    chdir: "{{ aap_dir }}"
  async: 5000
  poll: 15
